export const SEXOS_MASCOTA = ["MACHO", "HEMBRA"] as const;

export type SexoMascota = typeof SEXOS_MASCOTA[number];

export const SEXO_LABEL: Record<SexoMascota, string> = {
  MACHO: "Macho",
  HEMBRA: "Hembra",
};

export const ESPECIES = [
  "Perro",
  "Gato",
  "Ave",
  "Reptil",
  "Conejo",
  "Hurón",
  "Hámster",
  "Pez",
  "Tortuga",
  "Cobaya",
  "Erizo",
] as const;

export type Especie = typeof ESPECIES[number];

export const RAZAS_POR_ESPECIE: Record<string, string[]> = {
  Perro: [
    "Mestizo",
    "Labrador Retriever",
    "Golden Retriever",
    "Pastor Alemán",
    "Bulldog Francés",
    "Bulldog Inglés",
    "Poodle (Caniche)",
    "Beagle",
    "Rottweiler",
    "Dálmata",
    "Husky Siberiano",
    "Chihuahua",
    "Pomerania",
    "Yorkshire Terrier",
    "Shih Tzu",
    "Cocker Spaniel",
    "Boxer",
    "Doberman Pinscher",
    "Schnauzer",
    "Maltés",
    "Pug",
    "Border Collie",
    "Pembroke Welsh Corgi",
    "Dachshund (Teckel)",
    "San Bernardo",
    "Akita Inu",
    "Pit Bull",
    "American Staffordshire Terrier",
    "Weimaraner",
    "Vizsla",
    "Collie",
    "Setter Irlandés",
    "Terranova",
    "Greyhound",
    "Whippet",
    "Pastor Belga",
    "Bloodhound",
    "Basset Hound",
    "Chow Chow",
    "Shar Pei",
    "Pekingés",
    "Lhasa Apso",
    "West Highland White Terrier",
    "Jack Russell Terrier",
    "Cairn Terrier",
    "Boston Terrier",
    "Staffordshire Bull Terrier",
    "Cavalier King Charles Spaniel",
    "Papillón",
    "Chino Crestado",
  ],
  Gato: [
    "Mestizo",
    "Siamés",
    "Persa",
    "Maine Coon",
    "Ragdoll",
    "Bengalí",
    "British Shorthair",
    "Abisinio",
    "Sphynx",
    "Ruso Azul",
    "Birmano",
    "Bombay",
    "Burmés",
    "Exótico de Pelo Corto",
    "Himalayo",
    "Angora",
    "Somalí",
    "Devon Rex",
    "Cornish Rex",
    "Scottish Fold",
    "Singapura",
    "LaPerm",
    "Chartreux",
    "Korat",
    "Oriental",
    "Manx",
    "Savannah",
    "Chausie",
    "Snowshoe",
    "Tonkinés",
  ],
  Ave: [
    "Canario",
    "Periquito Australiano",
    "Cotorra Argentina",
    "Loro Gris Africano",
    "Agapornis (Inseparable)",
    "Jilguero",
    "Pinzón",
    "Diamante Mandarín",
    "Ninfa (Cockatiel)",
    "Cacatúa",
    "Guacamayo",
    "Yako",
    "Estornino",
  ],
  Reptil: [
    "Iguana Verde",
    "Gecko Leopardo",
    "Gecko Crestado",
    "Bearded Dragon (Pogona)",
    "Serpiente Ball (Píton Real)",
    "Serpiente Rey",
    "Tortuga de Orejas Rojas",
    "Camaleón Pantera",
    "Camaleón de Jackson",
    "Teju",
    "Varano",
    "Anolis Verde",
  ],
  Conejo: [
    "Holandés",
    "Mini Lop",
    "Angora",
    "Rex",
    "Flemish Giant",
    "Holland Lop",
    "Netherland Dwarf",
    "Lionhead",
    "Rex Neozelandés",
    "Californiano",
    "Chinchilla",
  ],
  Hurón: [
    "Hurón Europeo",
    "Hurón del Sable",
    "Hurón de Pelo Largo",
  ],
  "Hámster": [
    "Sirio (Dorado)",
    "Campbell",
    "Winter White",
    "Roborovski",
    "Chino",
  ],
  Pez: [
    "Goldfish (Carpa Dorada)",
    "Betta (Pez Siamés)",
    "Guppy",
    "Neón",
    "Angelfish (Pez Ángel)",
    "Ciclido Africano",
    "Pez Gato (Corydoras)",
    "Tetra",
    "Molly",
    "Platy",
    "Pez Espada",
    "Discus",
  ],
  Tortuga: [
    "Tortuga de Orejas Rojas",
    "Tortuga Margarita",
    "Tortuga Rusa",
    "Tortuga Pintada",
    "Tortuga Mojave",
    "Tortuga Caja",
    "Tortuga Leopardo",
  ],
  Cobaya: [
    "Abisinia",
    "Peruana",
    "Teddy",
    "Silkie",
    "Coronet",
    "Merino",
    "Baldwin",
  ],
  Erizo: [
    "Erizo Africano (Pigmeo)",
    "Erizo Europeo",
    "Erizo de Alborada",
  ],
};

export const CONDICIONES_REPRODUCTIVAS = [
  "Entero",
  "Castrado",
  "Gestante",
  "Lactante",
  "En celo",
  "Esterilizado",
] as const;
