export type { LoginRequest, RegisterRequest, AuthResponse, TokenRefreshResponse, ApiError } from "./authType";
export type { CitaResponse, CitaRequest, CitaEstadoRequest, CitaReprogramarRequest, DisponibilidadResponse } from "./citaType";
export type { ContactoEmergencia, ContactoEmergenciaRequest } from "./contactoType";
export type { UserRole, Dueno, DuenoRequest } from "./duenoType";
export type { MascotaRequest, MascotaResponse, CambioDuenoPrincipalRequest } from "./mascotaType";
export type { PaginatedResponse } from "./pagination";
export type { ServicioRequest, ServicioResponse } from "./servicioType";
export type { VeterinarioResponse } from "./usuarioType";
export type { TriajeRequest, TriajeResponse } from "./triajeType";
export type { SalaEsperaRequest, SalaEsperaEstadoRequest, SalaEsperaResponse } from "./salaEsperaType";
export type { AtencionClinicaRequest, AtencionClinicaResponse } from "./atencionClinicaType";
export type { DisponibilidadRequest, DisponibilidadVeterinarioResponse } from "./disponibilidadType";
export type { BloqueoRequest, BloqueoVeterinarioResponse } from "./bloqueoType";
export type { HistorialTransferenciaResponse } from "./transferenciaType";
