export type { LoginRequest, RegisterRequest, AuthResponse, TokenRefreshResponse, ApiError } from "./authType";
export type { CitaResponse, CitaRequest, CitaEstadoRequest, CitaReprogramarRequest, DisponibilidadResponse } from "./citaType";
export type { ContactoEmergencia, ContactoEmergenciaRequest } from "./contactoType";
export type { UserRole, Dueno, DuenoRequest } from "./duenoType";
export type { MascotaRequest, MascotaResponse, CambioDuenoPrincipalRequest } from "./mascotaType";
export type { PaginatedResponse } from "./pagination";
export type { ServicioRequest, ServicioResponse } from "./servicioType";
export type { VeterinarioResponse, UsuarioResponse, ActualizarUsuarioRequest, CambiarContrasenaRequest } from "./usuarioType";
export type { TriajeRequest, TriajeResponse } from "./triajeType";
export type { SalaEsperaRequest, SalaEsperaEstadoRequest, SalaEsperaResponse } from "./salaEsperaType";
export type { AtencionClinicaRequest, AtencionClinicaResponse } from "./atencionClinicaType";
export type { DisponibilidadRequest, DisponibilidadVeterinarioResponse } from "./disponibilidadType";
export type { BloqueoRequest, BloqueoVeterinarioResponse } from "./bloqueoType";
export type { HistorialTransferenciaResponse } from "./transferenciaType";
export type { AuditoriaResponse } from "./auditoriaType";
export type { MascotaAlertaResponse } from "./mascotaAlertaType";
export type { HistorialVacunacionRequest, HistorialVacunacionResponse } from "./vacunacionType";
export type { RecetaRequest, RecetaDetalleRequest, RecetaResponse, RecetaDetalleResponse } from "./recetaType";
export type { PlanTratamientoResponse, PlanTratamientoActividadResponse, PlanTratamientoRequest, PlanTratamientoActividadRequest } from "./planTratamientoType";
export type { ConsentimientoResponse, ConsentimientoRequest } from "./consentimientoType";
export type { SeguimientoResponse, SeguimientoRequest } from "./seguimientoType";
export type { NotificacionResponse } from "./notificacionType";
export type { DashboardResumen, ServicioTop, CitasPorEstado } from "./dashboardType";
